### ISSUE TITLE
How do I participate in JIRA?

### ISSUE THREAD

**Issue by btopro** [sakaiproject/sakai-reference#66]
So you don't use github issues (I don't entirely blame you) on https://github.com/sakaiproject/sakai/ and as a new person I'm looking at Jira which I stumbled on

https://github.com/sakaiproject/sakai/blob/master/CONTRIBUTING.md just says "you need a JIRA account"

Small tiny text I eventually found === that I can get an account
![2019-06-04_23-21-00](https://user-images.githubusercontent.com/329735/58934494-78af4880-871f-11e9-91e8-b6a97c6c3857.png)

Then when I click this, I can't make a JIRA
![2019-06-04_23-21-15](https://user-images.githubusercontent.com/329735/58934520-882e9180-871f-11e9-947d-3b89aaf11f72.png)

**Comment by bjones86** [comment]
We had to disable manual user creation in JIRA due to repeated spam attacks. I've sent an invitation to your email address which I think will allow you to create a user account. If this doesn't work, feel free to email me directly and I can create an account on your behalf.
